### ISSUE TITLE
Cannot update a component while rendering a different component warning

### ISSUE THREAD

**Issue by jackli921** [chingu-voyages/v44-tier2-team-24#43]
**Describe the problem**
Error

**Actual behavior**
Error mesage
React_devtools_backend_compact.js:2367 Warning: Cannot update a component (BotsInfo) while rendering a different component (App). To locate the bad setState() call inside App, follow the stack trace as described in https://reactjs.org/link/setstate-in-render at App (http://localhost:5174/src/App.jsx?t=1686082820835:30:37)

**Expected behavior**
No errors in the console

**To Reproduce**
Input the bot name and click "Create Bot" 

**Screenshots**
n/a

**Your Environment:**
Chrome

**Additional Information**
n/a

**Comment by libbyreeves** [comment]
I'll think about it.....

**Comment by jackli921** [comment]
still has one more re-rendering problem we haven't been able to debug.
arning: Cannot update a component (`App`) while rendering a different component (`BotsInfo`). To locate the bad setState() call inside `BotsInfo`

**Comment by jackli921** [comment]
Refactoring updateBotsData out of the setIconSelected setter function in BotsInfo.jsx removed the error
