### ISSUE TITLE
bot image is not selectable after a bot has been deleted

### ISSUE THREAD

**Issue by libbyreeves** [chingu-voyages/v44-tier2-team-24#47]
**Describe the problem**
After a bot has been selected and the user decides they no longer want that bot, they click the delete button. After the delete button has been pressed the bot icon is still greyed out as if it's been selected and in the array.

**Actual behavior**
Bot image cannot be selected after it has been deleted.

**Expected behavior**
Bot image should be re-selectable after the delete button has been clicked.

**To Reproduce**
1. go to createbot screen
2. fill in robot fields
3. press delete button
4. make another robot

**Screenshots**
If applicable, add screenshots or gifs to help explain your problem.

**Your Environment:**
 - Your browser & its version
 - Any other software that may impact this issue

**Additional Information**

**Comment by jackli921** [comment]
This bug has been fixed in the latest branch refactor-gameplay-total
