### ISSUE TITLE
XOR Operator: The bots don't move after touching the edges

### ISSUE THREAD

**Issue by sucheta90** [chingu-voyages/v44-tier2-team-24#63]
**Describe the problem**
This is an XOR specific problem where the bots after touching the edge of the arena stops moving at all and stays on the same location even though the timer keeps going.

**Actual behavior**
The Bots touching the edge of the battle field in XOR, stops moving and stays at the same position. The game has to be stopped manually.

**Expected behavior**
The bots are supposed to go in the other / calculated directions on hitting the edge of the battleground.

**Screenshots**
If applicable, add screenshots or gifs to help explain your problem.

**Your Environment:**
 - Google Chrome

**Comment by jackli921** [comment]
Fixed with commit 551d788
